name: AWS CI CD
on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허 브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 1. Java 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Spring Boot 애플리케이션 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Gradle 빌드 엑션을 이용해서 프로젝트 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      # 3. AWS 로그인
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::641022061021:role/awscicd
          role-session-name: sampleSessionName
          aws-region: ap-northeast-2
